ALTER TABLE client
ADD COLUMN gender VARCHAR(10);

ALTER TABLE membership
ADD COLUMN discount NUMERIC(5, 2) DEFAULT 0;

ALTER TABLE client
ALTER COLUMN phone TYPE VARCHAR(30);

ALTER TABLE visit
ADD COLUMN comment TEXT;
